# Generated by Django 4.0.5 on 2022-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='change', max_length=20),
            preserve_default=False,
        ),
    ]
