# Generated by Django 4.0.5 on 2022-06-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
