# Generated by Django 4.0.5 on 2022-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_remove_user_email_remove_user_f_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
    ]
